# -*- coding: utf-8 -*-
"""IMAGE_CAPTIONING.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k9b9g7yPNP41e7vnglEHkLCgfFf44bhl
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
import warnings
warnings.filterwarnings(action='ignore')

import numpy as np
from numpy import array
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import string
import os
from PIL import Image
import glob
from pickle import dump, load
from time import time
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Embedding, TimeDistributed, Dense, RepeatVector,\
                         Activation, Flatten, Reshape, concatenate, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam, RMSprop
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import add
from tensorflow.keras.applications.inception_v3 import InceptionV3
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import Model
from tensorflow.keras import Input, layers
from tensorflow.keras import optimizers
from tensorflow.keras.applications.inception_v3 import preprocess_input
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.callbacks import ModelCheckpoint

from os import listdir
from collections import Counter

def load_doc(filename):
    with open(filename) as file:
        text = file.readlines()
        return text

filename = "/content/drive/MyDrive/Flickr8k.token.txt"
text = load_doc(filename)
for line in text[:10]:
    print(line,end='')

def image_to_captions(text):
    hash_map = {}
    for line in text:
        token = line.split()
        image_id = token[0].split('.')[0] # separating with '.' to extract image id (removing .jpg)
        image_caption = ' '.join(token[1: ])
        
        if(image_id not in hash_map):
            hash_map[image_id] = [image_caption]
        else:
            hash_map[image_id].append(image_caption)
        
    return hash_map
        

map_img_to_captions = image_to_captions(text)
print(*map_img_to_captions['1000268201_693b08cb0e'],sep='\n')

def preprocess(map_img_to_captions):
    preprocessed_captions = []
    for key in map_img_to_captions.keys():
        for idx in range(len(map_img_to_captions[key])):
            tokens = map_img_to_captions[key][idx].split()
            tokens = [token.lower() for token in tokens if len(token)>1 if token.isalpha()]
            map_img_to_captions[key][idx] = ' '.join(tokens)
            
    return map_img_to_captions


preprocessed_map = preprocess(map_img_to_captions)
preprocessed_map['1000268201_693b08cb0e']

def create_vocabulary(preprocessed_map):
    vocabulary = set()
    for img_captions in preprocessed_map.values(): # list of 5 captions for each image
        for caption in img_captions:
            for token in caption.split():
                vocabulary.add(token)    
    return vocabulary


vocabulary = create_vocabulary(preprocessed_map)
print('Vocabulary size',len(vocabulary))

def img_id_train(filename):
    with open(filename) as file:
        data = file.readlines()
        train_img_name = []
        for img_id in data:
            train_img_name.append(img_id.split('.')[0])
    return train_img_name    

train_img_name = img_id_train('/content/drive/MyDrive/Flickr_8k.trainImages.txt')
test_img_name  = img_id_train('/content/drive/MyDrive/Flickr_8k.testImages.txt')
print(*train_img_name[:5],sep='\n')
print('\nNumber of images in train data',len(train_img_name))
print('\nNumber of images in train data',len(test_img_name))

def load_captions_train(filename):
    doc = load_doc(filename) 
    train_captions = {}    
    
    for line in doc:
        tokens = line.split()
        image_id, image_caption = tokens[0], tokens[1:]

        if(image_id in train_img_name):
            if(image_id not in train_captions):
                train_captions[image_id] = []
            
            modified_caption = 'startseq ' + ' '.join(image_caption) + ' endseq'
            train_captions[image_id].append(modified_caption)
    
    return train_captions


train_captions = load_captions_train('/content/drive/MyDrive/preprocessed_captions.txt')
print(*train_captions['1000268201_693b08cb0e'],sep='\n')

def preprocess_image(img_path):
    img = image.load_img(img_path,target_size=(299,299)) 
    # type(img): PIL.Image.Image
#     plt.figure(figsize=(12,6))
#     plt.subplot(121)
#     plt.imshow(img)
#     plt.title('Original Image(Resized)')

    img = image.img_to_array(img) # Converts PIL Image instance to numpy array (299,299,3)
    img = np.expand_dims(img, axis=0) #Add one more dimension: (1, 299, 299, 3) # Inception-V3 requires 4 dimensions
    img = preprocess_input(img) # preprocess image as per Inception-V3 model
#     plt.subplot(122)
#     plt.imshow(img[0])
#     plt.title('Preprocessed image for Inception-V3')    
    
    return img  # shape: (1, 299, 299, 3)

import tensorflow as tf

image_model = InceptionV3(include_top=False,weights='imagenet')
new_input = image_model.input
hidden_layer = image_model.layers[-1].output
model_new = tf.keras.Model(new_input, hidden_layer)

# Load Inception-V3 model
model = InceptionV3(weights='imagenet')

# Create new model, by removing last layer (output layer) from Inception-V3
model_new = Model(inputs=model.input, outputs=model.layers[-2].output) # outputs=(second last layer output)

# model.layers            list of layers
# model.input             <tf.Tensor 'input_1:0' shape=(?, ?, ?, 3) dtype=float32>
# model.layers[-1].output <tf.Tensor 'predictions/Softmax:0' shape=(?, 1000) dtype=float32> 1000 target classes
# model.layers[-2].output <tf.Tensor 'avg_pool/Mean:0' shape=(?, 2048) dtype=float32>

from tqdm import tqdm

train_features = {}
for i in tqdm(train_captions):
  img = preprocess_image("/content/drive/MyDrive/IMAGE CAPTIONING/Flicker8k_Dataset/"+str(i)+".jpg")
  pred = model_new.predict(img)
  train_features[i] = pred

train_features = load(open("/content/drive/MyDrive/encoded_train_images.pkl", "rb"))

# Create a list of all the training captions
all_train_captions = []
for captions in train_captions.values():
    for caption in captions:
        all_train_captions.append(caption)
    
print(len(all_train_captions))
print(*all_train_captions[:10],sep='\n')

corpus = []
for caption in all_train_captions:
    for token in caption.split():
        corpus.append(token)
        
hash_map = Counter(corpus)
vocab = []
for token,count in hash_map.items():
    if(count>=10):
        vocab.append(token)
        
print('Number of original tokens',len(hash_map))
print('Number of tokens after threshold',len(vocab))

word_to_index = {}
index_to_word = {}
    
for idx,token in enumerate(vocab):
    word_to_index[token] = idx+1
    index_to_word[idx+1] = token

vocab_size = len(index_to_word) + 1 # one for appended 0's

print(len(index_to_word))

def max_len_caption(all_train_captions):   
    max_len = 0
    for caption in all_train_captions:
        max_len = max(max_len,len(caption.split()))
    print('Maximum length of caption= ',max_len)
    return max_len

max_length_caption = max_len_caption(all_train_captions)

train_captions

temp='Flicker8k_Dataset/'
X1, X2, y = list(), list(), list() 
for key, des_list in train_captions.items(): 
	pic = train_features[temp+key +'.jpg'] 
	for cap in des_list: 
		seq = [word_to_index[word] for word in cap.split(' ') if word in word_to_index] 
		for i in range(1, len(seq)): 
			in_seq, out_seq = seq[:i], seq[i] 
			in_seq = pad_sequences([in_seq], maxlen = max_length_caption)[0] 
			out_seq = to_categorical([out_seq], num_classes = vocab_size)[0] 
			# store 
			X1.append(pic) 
			X2.append(in_seq) 
			y.append(out_seq) 

X2 = np.array(X2) 
X1 = np.array(X1) 
y = np.array(y) 1

X2.shape

y.shape

X1.shape

vocab

embeddings_index = {} # empty dictionary
f = open('/content/drive/MyDrive/glove.6B.200d.txt', encoding="utf-8")

for line in f:
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index[word] = coefs
f.close()

print('Found %s word vectors.' % len(embeddings_index))

embedding_dim = 200

# Get 200-dim dense vector for each of the 10000 words in out vocabulary
embedding_matrix = np.zeros((vocab_size, embedding_dim))

for word, i in word_to_index.items():
    #if i < max_words:
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        # Words not found in the embedding index will be all zeros
        embedding_matrix[i] = embedding_vector
        
embedding_matrix.shape

inputs1 = Input(shape=(2048,))
fe1 = Dropout(0.5)(inputs1)
fe2 = Dense(256, activation='relu')(fe1)
inputs2 = Input(shape=(max_length_caption,))
se1 = Embedding(vocab_size, embedding_dim, mask_zero=True)(inputs2)
se2 = Dropout(0.5)(se1)
se3 = LSTM(256)(se2)
decoder1 = add([fe2, se3])
decoder2 = Dense(256, activation='relu')(decoder1)
outputs = Dense(vocab_size, activation='softmax')(decoder2)
model = Model(inputs=[inputs1, inputs2], outputs=outputs)
model.summary()

model.layers[2].set_weights([embedding_matrix])
model.layers[2].trainable = False

model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

model.fit([X1, X2], y, epochs = 100, batch_size = 512)

def greedy_search(pic): 
    start = 'startseq'
    for i in range(max_length_caption): 
        seq = [word_to_index[word] for word in start.split() if word in word_to_index] 
        seq = pad_sequences([seq], maxlen = max_length_caption) 
        yhat = model.predict([pic, seq]) 
        yhat = np.argmax(yhat) 
        word = index_to_word[yhat] 
        start += ' ' + word 
        if word == 'endseq': 
            break
    final = start.split() 
    final = final[1:-1] 
    final = ' '.join(final) 
    return final

test_features = load(open("/content/drive/MyDrive/encoded_test_images.pkl", "rb"))

pred = greedy_search(test_features['Flicker8k_Dataset/2594042571_2e4666507e.jpg'].reshape(1,2048))

from nltk.translate.bleu_score import sentence_bleu

sentence_bleu(preprocessed_map['2594042571_2e4666507e'],pred)

pred_good, pred_bad, bleus = [], [], [] 
for img in test_features.keys():
  pred = greedy_search(test_features[img].reshape(1,2048))
  bleu = sentence_bleu(preprocessed_map[img.split('/')[1].split('.')[0]],pred )
  bleus.append(bleu)
  if bleu > 0.8 and len(pred_good) < 5:
      pred_good.append([img,bleu])
  elif bleu < 0.3 and len(pred_bad) < 5:
      pred_bad.append([img,bleu])
  if len(pred_good)==5 and len(pred_bad)==5 :
    break

pred = greedy_search(test_features['Flicker8k_Dataset/514990193_2d2422af2c.jpg'].reshape(1,2048))
img = image.load_img('514990193_2d2422af2c.jpg',target_size=(299,299)) 
plt.imshow(img)
print(pred)

!mkdir -p saved_model
model.save('saved_model/my_model500.h5')

